### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by TheNomad11** [weidi/softether-docker#1]
How to use it after running the docker command in the readme?

**Comment by weidi** [comment]
Hi, 

usage is like if you would run the binary normally. 
So you can use the UI Tools "SoftEther VPN Server Manager" either for Windows or OS X.
You can download them: [here](http://www.softether-download.com/en.aspx?product=softether)

Just connect to the IP of the docker host and the firststart wizard will pop up

**Comment by TheNomad11** [comment]
Thanks a lot! Now I've made it work
