### ISSUE TITLE
Image for Bridge Only

### ISSUE THREAD

**Issue by Odianosen25** [weidi/softether-docker#2]
Hello @weidi,

Thanks for this. Pls will it be possible to release a docker file, for the bridge only?

Kind regards

**Comment by Odianosen25** [comment]
Don't worry, I was able to create it by simply making changes to where you have `vpn_server` or `vpnserver` to `vpn_bridge` or `vpnbridge` respecively. Just in case someone else has the same query.

Kind regards for this again, and I have waited for good part of a year for someone to release this in alpine.

**Comment by weidi** [comment]
Hi @Odianosen25,
i just created a vpnbridge branch to build this as well when there are changes. Just pushed as "toprock/softether:vpnbridge"
