### ISSUE TITLE
JSON RPC Api

### ISSUE THREAD

**Issue by Odianosen25** [weidi/softether-docker#3]
Hello @weidi,

Please one thing I have noticed since I started using the docker container, is that I got no access to the api.  I can view the web interface as normal,  but HTTP requests to the api doesn't work. I keep getting the following response

```
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Any possibility you have come across this please?

Kind regards

**Comment by weidi** [comment]
Hi @Odianosen25 , what tag are you using? Looks like you are using python, are you trying to access https or http?
I haven´t testing API access as i was expecting if HTTPs is working the REST API should be good as well but i´d like to test this as well.

**Comment by Odianosen25** [comment]
Hello @weidi,

Thanks for the quick response. Thinking about it, I think I am using the latest tag, which is the one in dev, and I think I shouldn't be using that. Yes I am using python, and using `https`. 

Can I can't seem to figure out your build file for stable, will like to try that instead. Maybe it will fix my issue

Kind regards

**Comment by Odianosen25** [comment]
Hello @weidi,

I am sorry just being a nuisance again. I was actually using dev and not stable.

Thanks again for the file.

Kind regards

**Comment by weidi** [comment]
> Hello @weidi,
> 
> I am sorry just being a nuisance again. I was actually using dev and not stable.
> 
> Thanks again for the file.
> 
> Kind regards

You might just report this to softether they might be interested in it

**Comment by Odianosen25** [comment]
Done that just now, thanks

**Comment by weidi** [comment]
I´m struggling with the same issue now but want to use dev version. Have you managed to come around this ?

**Comment by Odianosen25** [comment]
Hello @weidi,

I never got it to work for dev, so just using stable as that’s enough for me at least for now. 

Are there any interesting features in dev that wants you want to use it, if I may ask please?

Thanks

**Comment by weidi** [comment]
Think there are loads of small fixes but nothing really necessary (in my case) just want to make it work even on latest & greatest ;)
