### ISSUE TITLE
Why vpncmd not copied?

### ISSUE THREAD

**Issue by aztecrabbit** [weidi/softether-docker#5]
vpncmd is useful for me, why not copied?

**Comment by weidi** [comment]
Hi @aztecrabbit, i wanted to keep the image as small as possible, if you want I can build one for this case and distribute with a separate tag. Optimally you use a separate container running vpncmd or having vpncmd on your PC and connecting to the container.

**Comment by aztecrabbit** [comment]
vpncmd is only 29.6 KB, and the library needed is the same as vpnserver, I think 29.6 KB is very small

**Comment by weidi** [comment]
Updated latest and 5.01.9674 and added vpncmd so you can use it like 
`docker exec -it softether-vpn-server vpncmd`
074c33a1f153a13f12637e7fe8d820ca37b664de

**Comment by aztecrabbit** [comment]
Hi, thank you very much @weidi for this very quick response, I will close this issue for now
