### ISSUE TITLE
Bridge connection

### ISSUE THREAD

**Issue by shock-wave007** [weidi/softether-docker#6]
Iam new to VPN and networking

There is a VPN server without lT2p enable so iam not able to connect it with my Android 

Is it possible to connect to that vpn server and create my own vpn with that connection with lT2p so I can connect it on my android

**Comment by weidi** [comment]
In theorie it is possible but that would require a lot of manual "tuning" of your "intermediate" VPN Server. 
What protocol is that existing VPN Server offering?

**Comment by shock-wave007** [comment]
It is a softether server and i don't know it's protocol(most probably default).
On softether client, I enter IP port 443 and username and password standard auth. 

I tried creating intermediate vpn , i successfully created softether server with lT2p but as soon as I try to connect my server with existing vpn and do some config i lost the SSH connection and then have to restart the VM.

Thanks for ur reply. And it's okay if there is no practical solution. Coz creating a intermediate server to change protocol is from my imagination 😅.

And i am open for any ideas u have.

**Comment by weidi** [comment]
You should raise these question in the SoftetherVPN repository as i´m just building that docker container. Never tried that but think you would need that cascade connection feature
![image](https://user-images.githubusercontent.com/2188062/147441800-99be7e99-4646-4664-bcce-173ebe78b74a.png)

**Comment by shock-wave007** [comment]
thanks for your time.
