### ISSUE TITLE
L2TP over IPsec not working

### ISSUE THREAD

**Issue by starlessboi** [weidi/softether-docker#7]
Hi
I have a problem in using your container for connecting to l2tp over ipsec protocol
the error is: The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.
nothing special in container logs
can anyone help me to know how can i t-shoot the reason and solve this error
btw openvpn protocol is working problem

thanks in advance

**Comment by weidi** [comment]
Hi @starlessboi, can you share logs from the container, you can get them by ``docker logs container-name``
Also is there any firewall or NAT gateway in between and are ports forwarded (UDP 500, 1701 and 4500)?

**Comment by starlessboi** [comment]
Hi
sure
this log is constantly showing in container log:
139954790386488:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:
139954790386488:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:

there is no nat or firewall..public ip is assigned to VM directly
i don't understand the last part... of forwarding
I'm using docker compose version with this config for ports:
    ports:
      - 53:53
      - 444:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp

should i do other things?
thank you for your time.

**Comment by weidi** [comment]
Looks like an issue with the openssl library used.
What image tag did you use?
Could you try with softethervpn/vpnserver:stable (just making it public) ;)

BR
Johannes

Am Mo., 11. Juli 2022 um 11:53 Uhr schrieb Mohammad <
***@***.***>:

**Comment by starlessboi** [comment]
i'm using the image, acoording to repo docker compose file:
toprock/softether:latest
---
changed the image to the one you said...problem solved!
but the below logs appears in container logs..
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found

installed iptables into container..then the errors gone
commands:
docker exec -it softether /bin/sh
apk add iptables

thanks again for your time , and great job

**Comment by weidi** [comment]
Good finding! This is just a "warning" but will implement it publicly.
